/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.triviaquirkproject;

import javax.swing.ButtonGroup;

/**
 *
 * @author Arnold
 */
public class GameSelection extends javax.swing.JFrame {

    private final ButtonGroup buttonGroup;
    
    /**
     * Creates new form GameSelection
     */
    public GameSelection() {
        initComponents();
        buttonGroup = new ButtonGroup();
        buttonGroup.add(chekbCine);
        buttonGroup.add(checkbHistoria);
        buttonGroup.add(checkbCiencia);
        buttonGroup.add(checkbSorpresa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEscogerCategoria = new javax.swing.JLabel();
        chekbCine = new javax.swing.JCheckBox();
        checkbHistoria = new javax.swing.JCheckBox();
        checkbCiencia = new javax.swing.JCheckBox();
        checkbSorpresa = new javax.swing.JCheckBox();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEscogerCategoria.setText("Escoger las categorias que deseas usar");

        chekbCine.setText("Cine");

        checkbHistoria.setText("Historia");

        checkbCiencia.setText("Ciencia y Tecnologia");

        checkbSorpresa.setText("Sorpresa");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEscogerCategoria)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chekbCine)
                    .addComponent(checkbCiencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbHistoria)
                    .addComponent(checkbSorpresa))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblEscogerCategoria)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekbCine)
                    .addComponent(checkbHistoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbCiencia)
                    .addComponent(checkbSorpresa))
                .addGap(42, 42, 42)
                .addComponent(btnSiguiente)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (chekbCine.isSelected()) {
            System.out.println("Cine seleccionado");
        } else if (checkbHistoria.isSelected()) {
            System.out.println("Historia seleccionada");
        } else if (checkbCiencia.isSelected()) {
            System.out.println("Ciencia y Tecnología seleccionada");
        } else if (checkbSorpresa.isSelected()) {
            System.out.println("Sorpresa seleccionada");
        } else {
            System.out.println("No se ha seleccionado ninguna opción");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox checkbCiencia;
    private javax.swing.JCheckBox checkbHistoria;
    private javax.swing.JCheckBox checkbSorpresa;
    private javax.swing.JCheckBox chekbCine;
    private javax.swing.JLabel lblEscogerCategoria;
    // End of variables declaration//GEN-END:variables
}
