/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.triviaquirkproject;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Arnold
 */
public class MultiLogin extends javax.swing.JFrame {
    int contador = 4;
    private Partida partidaActual;
    private String nombreJugador1;
    private String nombreJugador2;
    private String nombreJugador3;
    private String nombreJugador4;
    private ArrayList<Jugador> listaDeJugadores;
    private int numeroPartida;
    Categoria categoriaInstancia = new Categoria().getInstance();
    private ArrayList<String> categoriasSeleccionadas; 
    
    /**
     * Creates new form MultiLogin
     */
   
    public MultiLogin() {
        categoriasSeleccionadas = new ArrayList<>();
        listaDeJugadores = new ArrayList<>();
        initComponents();
       
        tfJugador3.setVisible(true);
        tfJugador4.setVisible(true);
        btnSiguiente.setVisible(false);
        chekbCine.setVisible(false);
        chekbHistoria.setVisible(false);
        chekbSorpresa.setVisible(false);
        chekbCiencia.setVisible(false);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        btnNumJugador.setText("4");
        
        //Crear un contador que empiece en 2
        
        //hacer una accion cada que clickee el btnnumjugador con el contador
        btnNumJugador.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
                System.out.println(contador);
                if (contador == 4) {
                    contador = 1;
                }
                if (contador >= 1 && contador <= 4) {
                    contador++;
                    if (contador == 3) {
                        btnNumJugador.setText("3");
                        tfJugador3.setVisible(true);
                        tfJugador4.setVisible(false);
                        jLabel3.setVisible(true);
                    } else if (contador == 4) {
                        btnNumJugador.setText("4");
                        tfJugador4.setVisible(true);
                        jLabel4.setVisible(true);
                    }
                if (contador == 2) {
                        btnNumJugador.setText("2");
                        tfJugador3.setVisible(false);
                        tfJugador4.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                    }
                }
                 
            }
        });
        
    }
    
     

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        chekbCine = new javax.swing.JCheckBox();
        chekbHistoria = new javax.swing.JCheckBox();
        chekbCiencia = new javax.swing.JCheckBox();
        chekbSorpresa = new javax.swing.JCheckBox();
        lblIngrese = new javax.swing.JLabel();
        tfJugador1 = new javax.swing.JTextField();
        tfJugador2 = new javax.swing.JTextField();
        tfJugador3 = new javax.swing.JTextField();
        tfJugador4 = new javax.swing.JTextField();
        btnNumJugador = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chekbCine.setText("Cine");
        chekbCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekbCineActionPerformed(evt);
            }
        });

        chekbHistoria.setText("Historia");
        chekbHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekbHistoriaActionPerformed(evt);
            }
        });

        chekbCiencia.setText("Ciencia y tecnologia");
        chekbCiencia.setToolTipText("");
        chekbCiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekbCienciaActionPerformed(evt);
            }
        });

        chekbSorpresa.setText("Sorpresa");
        chekbSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekbSorpresaActionPerformed(evt);
            }
        });

        lblIngrese.setText("Dele click para escoger la cantidad de jugadores");

        tfJugador1.setText("Jugador");

        tfJugador2.setText("Jugador");

        tfJugador3.setText("Jugador");

        tfJugador4.setText("Jugador");

        btnNumJugador.setText("2");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jButton1.setText("Añadir Jugadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jugador 1:");

        jLabel2.setText("Jugador 2:");

        jLabel3.setText("Jugador 3:");

        jLabel4.setText("Jugador 4:");

        jLabel5.setText("Unicamente puedes usar letras y numeros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(tfJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(chekbCine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chekbHistoria))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chekbCiencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chekbSorpresa))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIngrese)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSiguiente)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNumJugador)
                        .addGap(201, 201, 201))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIngrese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNumJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekbHistoria)
                    .addComponent(chekbCine))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekbCiencia)
                    .addComponent(chekbSorpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        // Verificar si se ha seleccionado al menos una categoría
    if (!chekbCine.isSelected() && !chekbHistoria.isSelected() && !chekbCiencia.isSelected() && !chekbSorpresa.isSelected()) {
        // Mostrar mensaje de error o cambiar el fondo a rojo
        // Ejemplo de mensaje de error:
        JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        //darle un color rojo al fondo
        //darle un color rojo al fondo
        chekbCiencia.setBackground(Color.red);
        chekbCine.setBackground(java.awt.Color.red);
        chekbHistoria.setBackground(java.awt.Color.red);
        chekbSorpresa.setBackground(java.awt.Color.red);
        
        return; // No continuar con el proceso
    }

    // Verificar la cantidad de jugadores seleccionados y validar los nombres
    int cantidadJugadores = Integer.parseInt(btnNumJugador.getText());
    tfJugador1.setBackground(java.awt.Color.white);
    tfJugador2.setBackground(java.awt.Color.white);
    tfJugador3.setBackground(java.awt.Color.white);
    tfJugador4.setBackground(java.awt.Color.white);
    switch (cantidadJugadores) {
        case 2:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    return; // No continuar con el proceso
                }
                break;
            case 3:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador") || tfJugador3.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador3.getText().equals("Jugador")) {
                        tfJugador3.setBackground(java.awt.Color.red);
                    }
                    

                    return; // No continuar con el proceso
                }
                break;
            case 4:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador") || tfJugador3.getText().equals("Jugador") || tfJugador4.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador3.getText().equals("Jugador")) {
                        tfJugador3.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador4.getText().equals("Jugador")) {
                        tfJugador4.setBackground(java.awt.Color.red);
                    }
                    return; // No continuar con el proceso
                }
                break;
        }
        //Crear los jugadores solo si el nombre no es igual a jugador y añadirlos a una lista jugadores
        ArrayList<Jugador> jugadores = new ArrayList<>();
        if (!tfJugador1.getText().equals("Jugador")) {
            Jugador jugador1 = new Jugador(tfJugador1.getText());
            jugadores.add(jugador1);
        }
        if (!tfJugador2.getText().equals("Jugador")) {
            Jugador jugador2 = new Jugador(tfJugador2.getText());
            jugadores.add(jugador2);
        }
        if (!tfJugador3.getText().equals("Jugador")) {
            Jugador jugador3 = new Jugador(tfJugador3.getText());
            jugadores.add(jugador3);
        }
        if (!tfJugador4.getText().equals("Jugador")) {
            Jugador jugador4 = new Jugador(tfJugador4.getText());
            jugadores.add(jugador4);
        }

        
        //Extraer la categoría seleccionada del bg
        String categoria = "";
        if (chekbCine.isSelected()) {
            categoria = "Cine";
        } else if (chekbHistoria.isSelected()) {
            categoria = "Historia";
        } else if (chekbCiencia.isSelected()) {
            categoria = "Ciencia Y Tecnologia";
        } else if (chekbSorpresa.isSelected()) {
            categoria = "Sorpresa";
        }
        if(categoriasSeleccionadas.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe escoger al menos una categoría de preguntas para poder jugar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            //this.dispose();
            numeroPartida = categoriaInstancia.registrarPartida();
            partidaActual = new Partida(numeroPartida); // Instancia unica - Singleton
            System.out.println(partidaActual.numeroPartida + " Validando en multijugador");
            for (Jugador jugadorActual : listaDeJugadores) {
                partidaActual.addJugador(jugadorActual);
            }
            for(String categorie : categoriasSeleccionadas){
                categoriaInstancia.agregarCategorias(categorie);
            }
            System.out.println(categoriaInstancia.obtenerCategorias());
            System.out.println(partidaActual);
            PlayGame jugar = new PlayGame(categoriaInstancia, partidaActual);  
           
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private boolean validateName(String username){
        String regex = "^[a-zA-Z0-9]+$";

        // Verificar si el nombre del jugador cumple con la expresión regular
        
        if ((username.matches(regex))){
            if (username.matches("Jugador")){
            return false;
            }       
            return true;
        } else {
            return false;
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(tfJugador1.isVisible()){
            nombreJugador1 = tfJugador1.getText();
            System.out.println(nombreJugador1);
            Jugador jugadorAgregar = new Jugador(nombreJugador1);
            if(validateName(nombreJugador1)){
                listaDeJugadores.add(jugadorAgregar);
            }else {
            // El nombre del jugador no es válido
            tfJugador1.setText("");
            tfJugador2.setText("");
            tfJugador3.setText("");
            tfJugador4.setText("");
            jLabel5.setForeground(Color.RED);
            }    
        } 
        if(tfJugador2.isVisible()){
            nombreJugador2 = tfJugador2.getText();
            Jugador jugadorAgregar = new Jugador(nombreJugador2);
            if(validateName(nombreJugador2)){
                listaDeJugadores.add(jugadorAgregar);
            }else {
            // El nombre del jugador no es válido
            tfJugador1.setText("");
            tfJugador2.setText("");
            tfJugador3.setText("");
            tfJugador4.setText("");
            jLabel5.setForeground(Color.RED);
            }    
        } 
        if(tfJugador3.isVisible()){
            nombreJugador3 = tfJugador3.getText();
            Jugador jugadorAgregar = new Jugador(nombreJugador3);
            if(validateName(nombreJugador3)){
                listaDeJugadores.add(jugadorAgregar);
            }else {
            // El nombre del jugador no es válido
            System.out.println("Nombre del jugador no válido. Solo se permiten letras y números.");
            tfJugador1.setText("");
            tfJugador2.setText("");
            tfJugador3.setText("");
            tfJugador4.setText("");
            jLabel5.setForeground(Color.RED);
            }    
        }
        if(tfJugador4.isVisible()){
            nombreJugador4 = tfJugador4.getText();
            Jugador jugadorAgregar = new Jugador(nombreJugador2);
            if(validateName(nombreJugador4)){
                listaDeJugadores.add(jugadorAgregar);
            } else {
            // El nombre del jugador no es válido
            tfJugador1.setText("");
            tfJugador2.setText("");
            tfJugador3.setText("");
            tfJugador4.setText("");
            jLabel5.setForeground(Color.RED);
            }    
        }
        if(listaDeJugadores.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe Llenar los campos de los jugadores", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            System.out.println("AquiToy con elementos");
            jLabel5.setForeground(Color.BLACK);
            tfJugador1.setVisible(false);
            tfJugador2.setVisible(false);
            tfJugador3.setVisible(false);
            tfJugador4.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(false);
            chekbCine.setVisible(true);
            chekbHistoria.setVisible(true);
            chekbSorpresa.setVisible(true);
            chekbCiencia.setVisible(true);
            btnSiguiente.setVisible(true);
            lblIngrese.setVisible(false);
            btnNumJugador.setVisible(false);
            
            return ;    
        }
        
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chekbCienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekbCienciaActionPerformed
        // TODO add your handling code here:
        if(chekbCiencia.isSelected()){
            categoriasSeleccionadas.add("Ciencia Y Tecnologia");
        } else {
            categoriasSeleccionadas.remove("Ciencia Y Tecnologia");
        }
    }//GEN-LAST:event_chekbCienciaActionPerformed

    private void chekbCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekbCineActionPerformed
        // TODO add your handling code here:
        if(chekbCine.isSelected()){
            categoriasSeleccionadas.add("Cine");
        } else {
            categoriasSeleccionadas.remove("Cine");
        }
    }//GEN-LAST:event_chekbCineActionPerformed

    private void chekbHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekbHistoriaActionPerformed
        // TODO add your handling code here:
        if(chekbHistoria.isSelected()){
            categoriasSeleccionadas.add("Historia");
        } else {
            categoriasSeleccionadas.remove("Historia");
        }
    }//GEN-LAST:event_chekbHistoriaActionPerformed

    private void chekbSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekbSorpresaActionPerformed
        // TODO add your handling code here:
        if(chekbSorpresa.isSelected()){
            categoriasSeleccionadas.add("Sorpresa");
        } else {
            categoriasSeleccionadas.remove("Sorpresa");
        }
    }//GEN-LAST:event_chekbSorpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MultiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNumJugador;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox chekbCiencia;
    private javax.swing.JCheckBox chekbCine;
    private javax.swing.JCheckBox chekbHistoria;
    private javax.swing.JCheckBox chekbSorpresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIngrese;
    private javax.swing.JTextField tfJugador1;
    private javax.swing.JTextField tfJugador2;
    private javax.swing.JTextField tfJugador3;
    private javax.swing.JTextField tfJugador4;
    // End of variables declaration//GEN-END:variables
}
