/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.triviaquirkproject;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Arnold
 */
public class MultiLogin extends javax.swing.JFrame {
    int contador = 4;
   
    /**
     * Creates new form MultiLogin
     */
   
    public MultiLogin() {
        initComponents();
        //colocar los checkb en un gruo para que solo se seleccione uno
        ButtonGroup bg = new ButtonGroup();
        bg.add(chekbCine);
        bg.add(chekbHistoria);
        bg.add(chekbCiencia);
        bg.add(chekbSorpresa);
        tfJugador3.setVisible(false);
        tfJugador4.setVisible(false);
        tfJugador3.setVisible(rootPaneCheckingEnabled);
        tfJugador4.setVisible(rootPaneCheckingEnabled);
        btnNumJugador.setText("4");
        
        //Crear un contador que empiece en 2
        
        //hacer una accion cada que clickee el btnnumjugador con el contador
        btnNumJugador.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
                System.out.println(contador);
                if (contador == 4) {
                    contador = 1;
                }
                if (contador >= 1 && contador <= 4) {
                    contador++;
                    if (contador == 3) {
                        btnNumJugador.setText("3");
                        tfJugador3.setVisible(true);
                        tfJugador4.setVisible(false);
                    } else if (contador == 4) {
                        btnNumJugador.setText("4");
                        tfJugador4.setVisible(true);
                    }
                if (contador == 2) {
                        btnNumJugador.setText("2");
                        tfJugador3.setVisible(false);
                        tfJugador4.setVisible(false);
                    }
                }
                 
            }
        });
        
    }
    
     

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        chekbCine = new javax.swing.JCheckBox();
        chekbHistoria = new javax.swing.JCheckBox();
        chekbCiencia = new javax.swing.JCheckBox();
        chekbSorpresa = new javax.swing.JCheckBox();
        lblIngrese = new javax.swing.JLabel();
        tfJugador1 = new javax.swing.JTextField();
        tfJugador2 = new javax.swing.JTextField();
        tfJugador3 = new javax.swing.JTextField();
        tfJugador4 = new javax.swing.JTextField();
        btnNumJugador = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chekbCine.setText("Cine");

        chekbHistoria.setText("Historia");

        chekbCiencia.setText("Ciencia");

        chekbSorpresa.setText("Sorpresa");

        lblIngrese.setText("Ingrese la cantidad de jugadores");

        tfJugador1.setText("Jugador");

        tfJugador2.setText("Jugador");

        tfJugador3.setText("Jugador");

        tfJugador4.setText("Jugador");

        btnNumJugador.setText("2");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chekbCiencia)
                        .addGap(59, 59, 59)
                        .addComponent(btnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chekbSorpresa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chekbCine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chekbHistoria)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJugador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblIngrese))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnNumJugador)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngrese)
                .addGap(15, 15, 15)
                .addComponent(btnNumJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chekbCine)
                    .addComponent(chekbHistoria))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chekbCiencia)
                            .addComponent(chekbSorpresa))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        // Verificar si se ha seleccionado al menos una categoría
    if (!chekbCine.isSelected() && !chekbHistoria.isSelected() && !chekbCiencia.isSelected() && !chekbSorpresa.isSelected()) {
        // Mostrar mensaje de error o cambiar el fondo a rojo
        // Ejemplo de mensaje de error:
        JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        //darle un color rojo al fondo
        //darle un color rojo al fondo
        chekbCiencia.setBackground(Color.red);
        chekbCine.setBackground(java.awt.Color.red);
        chekbHistoria.setBackground(java.awt.Color.red);
        chekbSorpresa.setBackground(java.awt.Color.red);
        
        return; // No continuar con el proceso
    }

    // Verificar la cantidad de jugadores seleccionados y validar los nombres
    int cantidadJugadores = Integer.parseInt(btnNumJugador.getText());
    tfJugador1.setBackground(java.awt.Color.white);
    tfJugador2.setBackground(java.awt.Color.white);
    tfJugador3.setBackground(java.awt.Color.white);
    tfJugador4.setBackground(java.awt.Color.white);
    switch (cantidadJugadores) {
        case 2:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    return; // No continuar con el proceso
                }
                break;
            case 3:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador") || tfJugador3.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador3.getText().equals("Jugador")) {
                        tfJugador3.setBackground(java.awt.Color.red);
                    }
                    

                    return; // No continuar con el proceso
                }
                break;
            case 4:
                if (tfJugador1.getText().equals("Jugador") || tfJugador2.getText().equals("Jugador") || tfJugador3.getText().equals("Jugador") || tfJugador4.getText().equals("Jugador")) {
                    // Mostrar mensaje de error o cambiar el fondo a rojo
                    // Ejemplo de mensaje de error:
                    JOptionPane.showMessageDialog(this, "Ingrese nombres válidos para los jugadores.", "Error", JOptionPane.ERROR_MESSAGE);
                    //darle un color rojo al fondo solo a los que esten en jugador
                    if (tfJugador1.getText().equals("Jugador")) {
                        tfJugador1.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador2.getText().equals("Jugador")) {
                        tfJugador2.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador3.getText().equals("Jugador")) {
                        tfJugador3.setBackground(java.awt.Color.red);
                    }
                    if (tfJugador4.getText().equals("Jugador")) {
                        tfJugador4.setBackground(java.awt.Color.red);
                    }
                    return; // No continuar con el proceso
                }
                break;
        }
        //Crear los jugadores solo si el nombre no es igual a jugador y añadirlos a una lista jugadores
        ArrayList<Jugador> jugadores = new ArrayList<>();
        if (!tfJugador1.getText().equals("Jugador")) {
            Jugador jugador1 = new Jugador(tfJugador1.getText());
            jugadores.add(jugador1);
        }
        if (!tfJugador2.getText().equals("Jugador")) {
            Jugador jugador2 = new Jugador(tfJugador2.getText());
            jugadores.add(jugador2);
        }
        if (!tfJugador3.getText().equals("Jugador")) {
            Jugador jugador3 = new Jugador(tfJugador3.getText());
            jugadores.add(jugador3);
        }
        if (!tfJugador4.getText().equals("Jugador")) {
            Jugador jugador4 = new Jugador(tfJugador4.getText());
            jugadores.add(jugador4);
        }
        //Imprimir los jugadores de la lista
        for (Jugador jugador : jugadores) {
            System.out.println(jugador.obtenerNombreJugador());
        }
        
        //Extraer la categoría seleccionada del bg
        String categoria = "";
        if (chekbCine.isSelected()) {
            categoria = "Cine";
        } else if (chekbHistoria.isSelected()) {
            categoria = "Historia";
        } else if (chekbCiencia.isSelected()) {
            categoria = "Ciencia";
        } else if (chekbSorpresa.isSelected()) {
            categoria = "Sorpresa";
        }
        System.out.println(categoria);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MultiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNumJugador;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox chekbCiencia;
    private javax.swing.JCheckBox chekbCine;
    private javax.swing.JCheckBox chekbHistoria;
    private javax.swing.JCheckBox chekbSorpresa;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIngrese;
    private javax.swing.JTextField tfJugador1;
    private javax.swing.JTextField tfJugador2;
    private javax.swing.JTextField tfJugador3;
    private javax.swing.JTextField tfJugador4;
    // End of variables declaration//GEN-END:variables
}
